version: "3.8"

services:
  event-finder-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - BROWSER_POOL_SIZE=${BROWSER_POOL_SIZE}
      - BROWSER_HEADLESS=${BROWSER_HEADLESS}
      - BROWSER_NAVIGATION_TIMEOUT=${BROWSER_NAVIGATION_TIMEOUT}
      - BROWSER_PAGE_TIMEOUT=${BROWSER_PAGE_TIMEOUT}
      - PLAYWRIGHT_BROWSERS_PATH=/home/appuser/.cache/ms-playwright
      - PYTHONPATH=/app
      - CELERY_LOG_LEVEL=INFO
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
